#!/usr/bin/env bash

# error_handler()
#
# Handles error when they are caught
function error_handler() {
    local -r exit_code="$?"
    local -r _line_number="$1"
    local -r command="$2"

    # shellcheck disable=SC2016
    if is_bound command && [[ "$command" != 'return $code' ]]; then
        log "  [${RED}x${RESET}] ${BOLD}ERROR ${DIM}${RED}$exit_code${RESET}${BOLD} → ${command}${RESET} "
    fi
    log ""

    for i in "${!BASH_SOURCE[@]}"; do
        if ! contains "errors.sh" "${BASH_SOURCE[$i]:-unknown}"; then
            log "    - ${FUNCNAME[$i]:-unknown}() ${ITALIC}${DIM}at line${RESET} ${BASH_LINENO[$i-1]:-unknown} ${ITALIC}${DIM}in${RESET} $(error_path "${BASH_SOURCE[$i]:-unknown}")"
        fi
    done
    log ""
}

set -Eeuo pipefail
trap 'error_handler $LINENO "$BASH_COMMAND"' ERR


SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source="./color.sh"
source "${SCRIPT_DIR}/color.sh"
# shellcheck source="./aliases.sh"
source "${SCRIPT_DIR}/aliases.sh"
# shellcheck source="./paths.sh"
source "${SCRIPT_DIR}/paths.sh"

TITLE="${TITLE:-${DIM:-}${ITALIC:-}your System}"

setup_colors
log ""
log "${BOLD}${YELLOW}About${RESET} ${TITLE}${RESET}"
log "---------------------------------------------"
log "${DIM}This system uses the ${ITALIC}adaptive shell${RESET}${DIM} bootstrap which provides${RESET}"
log "${DIM}functions, aliases, and installers based on the detected environment.${RESET}"
log ""

log "${BOLD}Aliases:${RESET}"
log "---------------------------------------------"
report_aliases

log ""
log "${BOLD}Executable ${RESET}${DIM}paths detected${RESET}${BOLD}:${RESET}"
log "---------------------------------------------"
report_paths

log ""
log "${BOLD}Functions:${RESET}"
log "- ${BLUE}${BOLD}sys${RESET}: provides up-to-date information about storage, networks,"
log "  editors, and more"
log "- ${BLUE}${BOLD}add${RESET}: function to install common programs setup a directory based on "
log "- ${BLUE}${BOLD}prep${RESET}: a ${ITALIC}context-aware${RESET} function which will detected programming"
log "  language(s) and install appropriate packages where appropriate"

remove_colors
